[common.indexer]
indexer_address = "0x1111111111111111111111111111111111111111"
operator_mnemonic = "abondon abondon abondon abondon abondon abondon abondon abondon abondon abondon abondon abondon abondon abondon abondon"

[common.server]
host_and_port = "0.0.0.0:7600"
url_prefix = "/"
free_query_auth_token = "free-query-auth-token"

[common.database]
postgres_url = "postgresql://arbtest:secret@localhost:5432/agent-db0"


[common.network_subgraph]
deployment = "QmXnGVrg6DvscnvJd86aHAPLGyGrkM17weMrAsFAEMmQLL"
query_url = "https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-arbitrum-sepolia"
recently_closed_allocation_buffer_seconds = 60
serve_subgraph = false
syncing_interval = 60

[common.escrow_subgraph]
deployment = "QmXnGVrg6DvscnvJd86aHAPLGyGrkM17weMrAsFAEMmQLL"
query_url = "https://gateway-arbitrum.network.thegraph.com/api/59e6a0d08017849c6633a6336de22c4b/subgraphs/id/7ubx365MiqBH5iUz6XWXWT8PTof5BVAyEzdb8m17RvbD"
serve_subgraph = false
syncing_interval = 300

[common.graph_network]
id = 1
chain_id = 421614

[common.scalar]
chain_id = 421614
# receipts_verifier_address = "0xac01B0b3B2Dc5D8E0D484c02c4d077C15C96a7b4"
receipts_verifier_address = "0xfC24cE7a4428A6B89B52645243662A02BA734ECF"
timestamp_error_tolerance = 30
receipt_max_value = 10000000000000000

[geo.geo_node]
status_url = "https://geo-conduit.up.railway.app/graphql"
query_base_url = "https://geo-conduit.up.railway.app"
