[package]
name = "indexer-common"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.6", features = ["serde"] }
alloy-sol-types = "0.6"
anyhow = "1.0.75"
arc-swap = "1.6.0"
ethers = "2.0.10"
ethers-core = "2.0.10"
eventuals = "0.6.7"
keccak-hash = "0.10.0"
lazy_static = "1.4.0"
prometheus = "0.13.3"
regex = "1.7.1"
reqwest = "0.12"
secp256k1 = { version = "0.28.0", features = ["recovery"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.117", features = ["arbitrary_precision"] }
sqlx = { version = "0.7.1", features = [
    "postgres",
    "runtime-tokio",
    "bigdecimal",
    "rust_decimal",
    "time",
] }
tokio = { version = "1.32.0", features = ["full", "macros", "rt"] }
thegraph = { git = "https://github.com/edgeandnode/toolshed", tag = "thegraph-v0.5.0" }
thegraph-graphql-http = { version = "0.2.1", features = [
    "http-client-reqwest",
] }
tap_core = "0.8.0"
axum = { version = "0.7.5", default_features = true }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
thiserror = "1.0.49"
async-trait = "0.1.74"
build-info = "0.0.34"
autometrics = { version = "1.0.1", features = ["prometheus-exporter"] }
tracing = "0.1.40"
tower_governor = "0.3.2"
tower-http = { version = "0.5.2", features = [
    "trace",
    "cors",
    "normalize-path",
] }
tokio-util = "0.7.10"
bigdecimal = "0.4.2"
serde-inline-default = "0.2.0"
thegraph-core = { version = "0.4.1", features = ["subgraph-client"] }

[dev-dependencies]
env_logger = "0.9.0"
test-log = "0.2.12"
wiremock = "0.5.19"
